name: Docker Image CI

on:
    push:
      branches: [ "master" ]
    workflow_dispatch:

jobs:

    build-base:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub Container Registry
        uses: docker/login-action@v3
        with:
          username: suro4ek
          password: ${{ secrets.TOKEN }}
      - name: Build and push base
        uses: docker/build-push-action@v5
        with:
          context: ./dockerfiles/base
          platforms: linux/arm64
          push: true
          tags: suro4ek/fenics:arm
          cache-from: type=registry,ref=suro4ek/fenics:arm-cache
          cache-to: type=registry,ref=suro4ek/fenics:arm-cache,mode=max

    build-base-amd64:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub Container Registry
        uses: docker/login-action@v3
        with:
          username: suro4ek
          password: ${{ secrets.TOKEN }}
      - name: Build and push base amd64
        uses: docker/build-push-action@v5
        with:
          context: ./dockerfiles/base-amd64
          platforms: linux/amd64
          push: true
          tags: suro4ek/fenics:amd64
          cache-from: type=registry,ref=suro4ek/fenics:amd64-cache
          cache-to: type=registry,ref=suro4ek/fenics:amd64-cache,mode=max

    build-vscode:
      runs-on: ubuntu-latest
      needs: build-base
      steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub Container Registry
        uses: docker/login-action@v3
        with:
          username: suro4ek
          password: ${{ secrets.TOKEN }}
      - name: Build and push vscode
        uses: docker/build-push-action@v5
        with:
          context: ./dockerfiles/vscode
          platforms: linux/arm64
          push: true
          tags: suro4ek/fenics:arm-vscode
          cache-from: type=registry,ref=suro4ek/fenics:arm-vscode-cache
          cache-to: type=registry,ref=suro4ek/fenics:arm-vscode-cache,mode=max

    build-torch:
      runs-on: ubuntu-latest
      needs: build-base
      steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub Container Registry
        uses: docker/login-action@v3
        with:
          username: suro4ek
          password: ${{ secrets.TOKEN }}
      - name: Build and push torch
        uses: docker/build-push-action@v5
        with:
          context: ./dockerfiles/torch
          platforms: linux/arm64
          push: true
          tags: suro4ek/fenics:arm-torch
          cache-from: type=registry,ref=suro4ek/fenics:arm-torch-cache
          cache-to: type=registry,ref=suro4ek/fenics:arm-torch-cache,mode=max
